server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server  # eureka实力主机名
  client:
    register-with-eureka: false # 不把自己注册进去
    fetch-registry: false # 不在eureka上获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka